"""
VinzClortho setup wizard.
Generates credentials for all registered Splipperverse services.
Run once per machine. The .env files are gitignored and never leave your box.
"""
from __future__ import annotations

import os
import secrets

ENV_FILE        = os.path.join(os.path.dirname(__file__), ".env")
SHOULDERS_ENV   = os.path.join(os.path.dirname(__file__), "../splippers.com/.env")

# Filled in during setup — do not change these manually
STRIPE_PRICE_ID = "price_1TZpG40hSs6KrAknRm8sqJEH"  # £19/month, live


def _prompt(label: str) -> str:
    return input(f"  {label}: ").strip()


def _generate_fernet_key() -> str:
    from cryptography.fernet import Fernet
    return Fernet.generate_key().decode()


# ── X.com ─────────────────────────────────────────────────────────────────────

def setup_x() -> list[str]:
    print("\n--- X.com ---")
    lines = []
    bearer = _prompt("Bearer Token (read-only, shared across all accounts)")
    lines.append(f"X_BEARER_TOKEN={bearer}")
    lines.append("")

    while True:
        nickname = input("\nAccount nickname (e.g. splippers) — Enter to skip: ").strip()
        if not nickname:
            break
        handle  = _prompt(f"X handle for {nickname} (without @)")
        key     = _prompt("API Key")
        secret  = _prompt("API Secret")
        token   = _prompt("Access Token")
        tsecret = _prompt("Access Token Secret")

        slug = nickname.upper().replace("@", "").replace(" ", "_")
        lines += [
            f"# @{handle} ({nickname})",
            f"X_{slug}_API_KEY={key}",
            f"X_{slug}_API_SECRET={secret}",
            f"X_{slug}_ACCESS_TOKEN={token}",
            f"X_{slug}_ACCESS_TOKEN_SECRET={tsecret}",
            "",
        ]

    return lines


# ── Shoulders (splippers.com store) ───────────────────────────────────────────

def setup_shoulders() -> None:
    print("\n--- Shoulders / store.splippers.com ---")
    print("  STRIPE_PRICE_ID is already set (£19/month, live)")
    print()
    print("  You need:")
    print("    1. STRIPE_SECRET_KEY  — Stripe Dashboard → Developers → API keys → Secret key")
    print("    2. STRIPE_WEBHOOK_SECRET — after you register the webhook URL in Stripe")
    print("    3. TOKEN_ENCRYPTION_KEY — will be generated automatically")
    print("    4. APP_BASE_URL — where the service will live (e.g. https://store.splippers.com)")
    print()

    sk = _prompt("STRIPE_SECRET_KEY (sk_live_...)")
    whsec = _prompt("STRIPE_WEBHOOK_SECRET (whsec_... — leave blank if not yet registered)")
    base_url = _prompt("APP_BASE_URL (default: https://store.splippers.com)")
    if not base_url:
        base_url = "https://store.splippers.com"

    enc_key = _generate_fernet_key()
    print(f"\n  Generated TOKEN_ENCRYPTION_KEY (save this — you can't recover it): {enc_key}")

    lines = [
        "# Shoulders — store.splippers.com",
        f"DATABASE_URL=sqlite:////data/splippers.db",
        f"APP_BASE_URL={base_url}",
        f"OAUTH_REDIRECT_URI={base_url}/auth/callback",
        "",
        "# Stripe",
        f"STRIPE_SECRET_KEY={sk}",
        f"STRIPE_WEBHOOK_SECRET={whsec}",
        f"STRIPE_PRICE_ID={STRIPE_PRICE_ID}",
        "",
        "# Token encryption (AES — generated by VinzClortho)",
        f"TOKEN_ENCRYPTION_KEY={enc_key}",
        "",
        "# Cloud storage OAuth apps",
        "# Google Drive",
        "GOOGLE_CLIENT_ID=",
        "GOOGLE_CLIENT_SECRET=",
        "# Dropbox",
        "DROPBOX_APP_KEY=",
        "DROPBOX_APP_SECRET=",
        "# OneDrive",
        "ONEDRIVE_CLIENT_ID=",
        "ONEDRIVE_CLIENT_SECRET=",
    ]

    target = os.path.abspath(SHOULDERS_ENV)
    os.makedirs(os.path.dirname(target), exist_ok=True)
    with open(target, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"\n  Written to {target}")
    if not whsec:
        print()
        print("  *** WEBHOOK NOT YET REGISTERED ***")
        print(f"  Once deployed, go to Stripe Dashboard → Developers → Webhooks")
        print(f"  Add endpoint: {base_url}/billing/webhook")
        print("  Events to listen for:")
        print("    checkout.session.completed")
        print("    customer.subscription.updated")
        print("    customer.subscription.deleted")
        print("  Then re-run this wizard (or manually edit the .env) to add STRIPE_WEBHOOK_SECRET.")


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    print("\n=== VinzClortho Setup Wizard ===")
    print("Are you the Keymaster? Good. Let's fill the gaps.\n")

    services = [
        ("x",        "X.com API credentials",           True),
        ("shoulders","Shoulders / store.splippers.com",  True),
    ]

    for key, label, _ in services:
        ans = input(f"\nConfigure {label}? [Y/n]: ").strip().lower()
        if ans in ("", "y", "yes"):
            if key == "x":
                lines = setup_x()
                with open(ENV_FILE, "w") as f:
                    f.write("\n".join(lines) + "\n")
                print(f"\n  X credentials saved to {ENV_FILE}")
            elif key == "shoulders":
                setup_shoulders()

    print("\n=== Done. VinzClortho is fully armed and operational. ===\n")


if __name__ == "__main__":
    main()
